### PR TITLE
WIP intellisense with inheritance for MeanModelWorkflow initializer

### PR DESCRIPTION
**Pull request by abdullahhamadeh**
addresses #524 

demo using "tests/dev/test-mean-nonparallel.R"

image

### CODE REVIEW

**Comment by abdullahhamadeh** [comment]
@pchelle, as discussed, I have tried simplifying the changes in this PR by simply extending the formals of the `MeanModelWorkflow` initializer, using  
`formals(MeanModelWorkflow$public_methods$initialize) <-  c(formals(Workflow$public_methods$initialize),formals(MeanModelWorkflow$public_methods$initialize))`
following the definition of the `MeanModelWorkflow` class.

What I'm seeing from initial testing, is that this isn't enough to modify the behavior.   The formals of `MeanModelWorkflow$new` do change, but the initializer doesn't seem to pass the arguments as expected.  I ran

```
rm(list = ls())
devtools::load_all(".")
formals(MeanModelWorkflow$public_methods$initialize) <-  c(formals(Workflow$public_methods$initialize),
                                                           formals(MeanModelWorkflow$public_methods$initialize))
ms <- SimulationSet$new(
  simulationSetName = "meansim",
  simulationFile = "./tests/data/input-data/individualPksimSim.pkml",
  outputs = Output$new(path = "Organism|Heart|Interstitial|smarties|Concentration")
)
mwf <- MeanModelWorkflow$new(simulationSets = list(ms), workflowFolder = "./ex")
```
which gave this error:

image

**Comment by msevestre** [comment]
Can you rebase/merge on develop so that we don't have so much noise from other PR

**Comment by msevestre** [comment]
Hey @abdullahhamadeh 
What are we trying to do here? It looks like you are writing some kind of meta framework around the default initialization? As this been approved by @Yuri05 ? I just want to be sure we are not working on nice to have features now if there are still some prio 1 to implement

**Comment by abdullahhamadeh** [comment]
Hi @msevestre 

#524 is labelled high priority - is this not the case?

I did discuss it with @Yuri05 at the jour fixe two weeks ago, and the idea is to extend this tool only to initializers that will be used by the typical user (ie no need to implement it to classes that are only used internally, by the developers). 
Right now we have intellisense for :
image

image

in addition to `MeanModelWorkflow$new`

The package installs and gives the intended behavior with these changes, but I am having trouble with documentation.  `devtools::document()` gives a bug:

image

which I have traced down to the use of the `formals` function.  In addition, documenting the parameters of the initializers that are to be created this way is not straightforward.  So this PR is something that I wanted to discuss at the next meeting.

**Comment by msevestre** [comment]
Ok I was not at the meeting. I am wondering if all the efforts is worth it. If @Yuri05 approved of this approach, I am fine. My train of thoughts was more along the way of doing it by hand since it's supposed to be only for the public class and not for all classes.

**Comment by abdullahhamadeh** [comment]
Yes I totally agree if we only restrict this to the few cases I mentioned.  I think the benefits will be more obvious if/when we extend this to public classes in `tlf` where we sometimes have more than one level of inheritance (see, eg, `DDIRatioPlotConfiguration`).   Then, any changes in arguments of a parent class constructor will automatically appear in the code completion of any child/grandchild class constructors.

**Comment by msevestre** [comment]
Will we move this to ospsuite.utils then?

**Pull request closed without merging**
