### PR TITLE
Fixes #837 enforce removal of Caption in legend title

### LINKED ISSUE #837: DDI Ratio plots: remove "Caption" from the legend
grafik

### PR DESCRIPTION
**Pull request by pchelle**
@Yuri05 I did not get this issue when testing with my current R version, could you check that this fix actually solved the issue

### CODE REVIEW

**Comment by Yuri05** [comment]
interesting.
Yes, fixed the issue on my comp!

**Comment by Yuri05** [comment]
@pchelle 
do we need to fix this issue for any other plot types (PK-ratio etc.)?

**Comment by pchelle** [comment]
The remaining plots should be okay, the issue came from `ggplot2::guide_legend` used in the ddi ratio plots that enforces the legend to stay in one unique column, however its side effect reset the title of the legend

**Comment by Yuri05** [comment]
ok, cool, thx!

**Pull request merged**
