### PR TITLE
Fixes #758 prevent plot area shrinking when saving plot

### LINKED ISSUE #758: Avoid "shrinking" of the plot area if the legend is above/below the plot
At the moment, if the legend is placed **above/below** the plot: `Legend.Height + PlotArea.Height = const`, meaning that the plot area is shrinking with every new legend entry.

Required is however: `PlotArea.Height = const` (or `PlotArea.Width : PlotArea.Height = const` )

### PR DESCRIPTION
**Pull request by pchelle**

### CODE REVIEW

**Comment by pchelle** [comment]
Comparison of what the same test plot before and after using `updatePlotDimensions` :
# Before
before

# After
after

**Comment by pchelle** [comment]
Works also on legend on the side

# Before
before

# After
after

**Comment by Yuri05** [comment]
Please rebase from develop

**Comment by Yuri05** [comment]
> Comparison of what the same test plot before and after using `updatePlotDimensions` :

Nice!
@sfrechen FYI

**Pull request merged**
