### PR TITLE
1007 update website

### PR DESCRIPTION
**Pull request by Yuri05**

### CODE REVIEW

**Comment by Yuri05** [comment]
@pchelle @msevestre Will merge if no concerns from your side till today EOB :)

**Comment by pchelle** [comment]
> @pchelle @msevestre Will merge if no concerns from your side till today EOB :)

Is there a simple way to review the rendered html and not the raw code ?
I recall there was an issue about a reference link that was not broken because of a lower/upper case issue in the file name

**Comment by Yuri05** [comment]
> Is there a simple way to review the rendered html and not the raw code ?

Clone the source branch of the PR locally and open **docs/index.html** in the web browser :)
No idea if it's possible directly on Github

**Comment by Yuri05** [comment]
> Is there a simple way to review the rendered html and not the raw code ?

https://htmlpreview.github.io/?https://github.com/Yuri05/OSPSuite.ReportingEngine/blob/1007_Update_website/docs/index.html

**Review by pchelle — APPROVED** [review]
From the preview, it seems everything works as expected in the documentation

**Pull request merged**
