### PR TITLE
Fixes #629 Always use the latest tlf version in the Windows builds

### LINKED ISSUE #629: Always use the latest tlf version in the Windows builds

### PR DESCRIPTION
**Pull request by Yuri05**

### CODE REVIEW

**Comment by Yuri05** [comment]
Using the permalink to the latest usccessfull AppVeyor Build of the tlf.
Now we can see that the Windows build fails because of 1 failed test (same as on Linux)
```
== Failed tests ================================================================
-- Error (test-pop-demography.R:69:1): (code run outside of `test_that()`) -----
Error in `unit(yticks$start, "cm")`: 'x' and 'units' must have length > 0
Backtrace:
     x
  1. \-workflowPediatric$runWorkflow() test-pop-demography.R:69:0
  2.   \-self[[plotTask]]$runTask(self$simulationStructures)
  3.     \-self$saveResults(taskResults)
  4.       \-ggplot2::ggsave(...)
  5.         +-grid::grid.draw(plot)
  6.         \-ggplot2:::grid.draw.ggplot(plot)
  7.           +-base::print(x)
  8.           \-ggplot2:::print.ggplot(x)
  9.             +-ggplot2::ggplot_gtable(data)
 10.             \-ggplot2:::ggplot_gtable.ggplot_built(data)
 11.               \-base::Map(...)
 12.                 \-base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
 13.                   \-(function (l, d) ...
 14.                     \-l$draw_geom(d, layout)
 15.                       \-ggplot2:::f(..., self = self)
 16.                         \-self$geom$draw_layer(...)
 17.                           \-ggplot2:::f(..., self = self)
 18.                             \-base::lapply(...)
 19.                               \-ggplot2:::FUN(X[[i]], ...)
 20.                                 +-base::do.call(self$draw_panel, args)
 21.                                 \-(structure(function (...) ...
 22.                                   \-ggplot2:::f(...)
 23.                                     +-base::with(...)
 24.                                     \-base::with.default(...)
 25.                                       \-base::eval(substitute(expr), data, enclos = parent.frame())
 26.                                         \-base::eval(substitute(expr), data, enclos = parent.frame())
 27.                                           +-grid::segmentsGrob(...)
 28.                                           | \-grid::is.unit(x0)
 29.                                           \-grid::unit(yticks$start, "cm")

[ FAIL 1 | WARN 63 | SKIP 0 | PASS 299 ]

```

**Comment by pchelle** [comment]
It is not failing on my computer after installing the `tlf` bundle. 
It makes troubleshooting harder.

From the testthat message, the crash happens in the pediatric demography plot (`test-pop-demography.R:69`). 
I'm going to check which plots may cause that.

**Comment by abdullahhamadeh** [comment]
> It is not failing on my computer after installing the `tlf` bundle. It makes troubleshooting harder.
> 
> From the testthat message, the crash happens in the pediatric demography plot (`test-pop-demography.R:69`). I'm going to check which plots may cause that.

@pchelle I think it is in the log plots, (line 200) in utilities-demography.R 
demographyPlots[[paste0(plotID, "-log")]] <- tlf::setYAxis(plotObject = vpcPlot, scale = tlf::Scaling$log)
Error in unit(yticks$start, "cm") : 'x' and 'units' must have length > 0

the linear plots seem ok

**Comment by msevestre** [comment]
cool!

**Pull request merged**
