### PR TITLE
Fixes #767 Deviation in pop time profile translated as range plot

### LINKED ISSUE #767: Why don't we have a Range plot when using mean + STD?
image

In PK-Sim. we have a range plot

/cc @Yuri05 @pchelle @abdullahhamadeh

### PR DESCRIPTION
**Pull request by pchelle**

### CODE REVIEW

**Comment by pchelle** [comment]
@msevestre 
In the configuration plan, the color is defined centrally in `Analysis`>`Fields`>`Color`
So the ranges and lines that summarize the simulations (in `Analysis`>`Statistics`) all get the same color

**Comment by pchelle** [comment]
Linux don't work because latest update on `{ospsuite}` require package `{patchwork}`

**Comment by msevestre** [comment]
Patchwork doesn't work on Linux?

**Comment by pchelle** [comment]
> Patchwork doesn't work on Linux?

The list of packages installed in linux depends on `.github/workflows/install_packages_cran.sh`
I have included it in the previous PR #763

**Comment by Yuri05** [comment]
Please rebase from develop

**Pull request merged**
