### PR TITLE
152 lloq

### PR DESCRIPTION
**Pull request by pchelle**
This PR encompasses PR #205 because I thought it would have been merged before I finish this one.

### CODE REVIEW

**Comment by Yuri05** [comment]
or, so I'm going to close #205 now?

**Comment by Yuri05** [comment]
@pchelle The test example from https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/208 (which is supposed to be fixed) now crashes with the code from this PR completely.
```
 [9] "04/06/2020 - 13:25:49 : R version: R version 3.5.2 (2018-12-20)" "04/06/2020 - 13:25:49 : OSP Suite Package version: 9.0.79"      
[11] "04/06/2020 - 13:25:49 : OSP Reporting Engine version: 1.0.38"    "04/06/2020 - 13:25:49 : tlf version: 1.0.64"                    
[1] "04/06/2020 - 13:25:49 : Starting run of population workflow"
[1] "04/06/2020 - 13:25:49 : Starting Perform simulation task"
[1] "04/06/2020 - 13:25:49 : Run simulation: Rifampin po, 450 mg, Bioequivalence - PopSim"
[1] "04/06/2020 - 13:26:01 : Starting: Plot Goodness of Fit task in Alpha Testing"
[1] "04/06/2020 - 13:26:01 : Report './Output_Workflow7/appendix-time-profile.md' was initialized successfully."
[1] "04/06/2020 - 13:26:01 : Plot Goodness of Fit task in Alpha Testing for Rifampin po, 450 mg, Bioequivalence - PopSim"
Error in data.frame(Time = observedDataset[rowFilter, timeColumn], Concentration = observedDataset[rowFilter,  : 
  arguments imply differing number of rows: 32, 0, 1
```

**Comment by pchelle** [comment]
The crash is due to the tpDictionary that indicates there is LLOQ data.
I can include some checking of existence of the variables within the dataset, so the user will know that the dictionary is not correct ?

**Comment by Yuri05** [comment]
OK, I see. 
After removing of lloq from the dictionary works fine. I will create another issue for the dictionary.
Going to merge for now.

**Pull request merged**
