### PR TITLE
Fixes #1079 prevent test that working directory to crash ratio workflow

### LINKED ISSUE #1079: test of population workflow fail for pk parameter ratio

### PR DESCRIPTION
**Pull request by pchelle**

### CODE REVIEW

**Comment by pchelle** [comment]
Weird
image

Is it because appveyor collects the fail artifact even if it does not exist ?
```yml
artifacts:
  - path: '*.Rcheck\**\*.fail'
    name: Logs
```
image

And just throws the last error from appveyor tests ?

**Comment by pchelle** [comment]
After deeper investigation, the error happens in `covr::codecov()`

**Comment by pchelle** [comment]
@Yuri05 could you re-launched the checks, appveyor did not go until the end

**Comment by Yuri05** [comment]
@pchelle Rebuilt; still 1 test failure in the code coverage :(

**Comment by Yuri05** [comment]
@pchelle Finally: all builds succeeded :)

**Comment by Yuri05** [comment]
@pchelle :champagne:

**Pull request merged**
