### PR TITLE
Fix #158

### LINKED ISSUE #158: Crash in population sensitivity plots
[CrashSensi.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4544711/CrashSensi.zip)

```
[1] "28/04/2020 - 11:32:36 : Starting: Plot Sensitivity task in Alpha Testing"
[1] "28/04/2020 - 11:32:36 : Plot Sensitivity task in Alpha Testing for Raltegravir 10 mg   (lactose formulation)"
Error in file.path(structureSet$workflowFolder, structureSet$sensitivityAnalysisResultsFolder,  :
  object 'pwf' not found
```

### PR DESCRIPTION
**Pull request by abdullahhamadeh**

### CODE REVIEW

**Comment by Yuri05** [comment]
@abdullahhamadeh TRying this PR I get the error message below
```
[1] "28/04/2020 - 20:40:05 : Starting: Plot Sensitivity task in Alpha Testing"
[1] "28/04/2020 - 20:40:05 : Plot Sensitivity task in Alpha Testing for Raltegravir 10 mg   (lactose formulation)"
[1] "28/04/2020 - 20:40:06 : Values 'Organism-Heart-Plasma-Raltegravir-Concentration' are not in included in parent values: 'Organism|Heart|Plasma|Raltegravir|Concentration'."
Error in logErrorThenStop(messages$errorNotIncluded(values, parentValues)) :
  Values 'Organism-Heart-Plasma-Raltegravir-Concentration' are not in included in parent values: 'Organism|Heart|Plasma|Raltegravir|Concentration'.
```

**Comment by msevestre** [comment]
where is such a string 'Organism-Heart-Plasma-Raltegravir-Concentration' coming from? This looks like a wrong path to me

**Comment by abdullahhamadeh** [comment]
I was using the output path as part of the file name for the sensitivity plot, but the "|" in the file path causes errors when saving the file.  So I replaced the "|" with "-".

**Comment by msevestre** [comment]
@abdullahhamadeh I am not sure I understand.
At any rate, it needs to be decoded again when used? We may have some - in paths so this might not work (user defined path etc.. as - is not prohibited)

**Comment by abdullahhamadeh** [comment]
No I don't think it would need to be decoded.  I just need a string that somehow represents the pathID of the output.  This string will be used only once, to name the sensitivity plot .png file.

**Comment by msevestre** [comment]
@abdullahhamadeh Then I do not understand why it's trying to match it to a path. Can you explain where this is happening?

`Values 'Organism-Heart-Plasma-Raltegravir-Concentration' are not in included in parent values: 'Organism|Heart|Plasma|Raltegravir|Concentration'.`

**Comment by abdullahhamadeh** [comment]
That's the bug, it shouldn't.  Testing fix now...

**Comment by abdullahhamadeh** [comment]
@Yuri05 is it the same example as in #158?

**Comment by Yuri05** [comment]
>It should work with the latest fix.

Yep, works now. However the plots can be improved ;)
First of all we should put the legend **above** the plot. @abdullahhamadeh Would you fix it as part of this PR or should we merge AS IS and create new Issues for this?
Raltegravir 10 mg   (lactose formulation)-Raltegravir Adult Population-C_max-Organism-Heart-Plasma-Raltegravir-Concentration

**Comment by msevestre** [comment]
Somewhere the user will be able to override the legend right?
E..g remove organism and call volume vol for ex

**Comment by abdullahhamadeh** [comment]
I moved the legend to the top.  I think a new issue is needed to address the oversized title and legend.

**Pull request merged**
