### PR TITLE
18 population time profiles

### PR DESCRIPTION
**Pull request by pchelle**

### CODE REVIEW

**Comment by Yuri05** [comment]
@pchelle This is WIP, right?
Cause I tried and got the error below:
```
[1] "24/04/2020 - 12:23:59 : Plot Goodness of Fit task in Alpha Testing for Raltegravir 10 mg   (lactose formulation)"
Error in enc2utf8(targetUnit) : argument is not a character vector
```

**Comment by pchelle** [comment]
Can you provide the code for the example or just let me know if you used a pathUnit ?
I will investigate and fix the bug

**Comment by Yuri05** [comment]
@pchelle here is an example 
[02_parallelcomparison.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4528824/02_parallelcomparison.zip)

**Comment by Yuri05** [comment]
@pchelle cool, works now. should we merge?

**Comment by msevestre** [comment]
Yes;-)

**Pull request merged**
