### PR TITLE
Add missing show progress option in analyze core sensitivity

### PR DESCRIPTION
**Pull request by abdullahhamadeh**

### CODE REVIEW

**Comment by msevestre** [comment]
There is an issue with the build I believe. For some reason, it does not run anymore.
We'll have to check it out

**Comment by msevestre** [comment]
It's because of the release of R4.0
We'll have to try to fix the release to 3.6 or sthg

**Comment by msevestre** [comment]
@abdullahhamadeh Can you please rebase on develop and submit your changes again?

**Comment by abdullahhamadeh** [comment]
All these changes are included in #156, which has been merged.   OK to close this PR.

**Comment by msevestre** [comment]
Closing then

**Pull request closed without merging**
